### ISSUE TITLE
Serverless notification modules doesnt work since 11.5.7

### ISSUE THREAD

**Issue by vasily-polonsky** [Adyen/adyen-commercetools#1220]
**Describe the bug**
In this release
[v11.5.7](https://github.com/Adyen/adyen-commercetools/releases/tag/v11.5.7)
logger was added to notificationHandler.processNotification as a parameter, but it was added only for microservices (controller) and not for serverless (aws lambda for example).

This leads to such errors ->

{
    "name": "ctp-adyen-integration-notifications",
    "hostname": "169.254.110.69",
    "pid": 8,
    "level": 50,
    "notification": [
        {
            "eventCode": "AUTHORISATION",
            "eventDate": "2024-11-15T12:27:05+01:00",
            "pspReference": "******",
            "success": "true"
        }
    ],
    "cause": {
        "message": "Cannot read properties of undefined (reading 'child')",
        "name": "TypeError",
        "stack": "TypeError: Cannot read properties of undefined (reading 'child')\n    at Object.processNotification (file:///var/task/src/handler/notification/notification.handler.js:15:28)\n    at Runtime.handler (file:///var/task/index.js:32:33)\n    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
    },
    "msg": "Unexpected exception occurred.",
    "time": "2024-11-15T11:27:05.658Z",
    "v": 0
}

**To Reproduce**
Invoke any event and code will fail

**Expected behavior**
Would be nice to have tests for serverless as well

**Comment by adyen-integrations-support** [comment]
Hi @vasily-polonsky ,

Thank you for reaching out to us. We have received your ticket and will review it as soon as possible. Our team will keep you updated on the progress and provide assistance promptly.

If you have any additional details to share, please feel free to reply to this email.

Best regards

**Comment by adyen-integrations-support** [comment]
Hi @vasily-polonsky ,

Thank you for your patience. We wanted to let you know that our team is still investigating the issue. We are working on identifying the cause and will keep you informed as soon as we have more information to share.

If you have any further details or questions in the meantime, please feel free to reach out.

Best regards

**Comment by adyen-integrations-support** [comment]
Hi @vasily-polonsky ,

Thank you for your continued patience. We wanted to assure you that our team is actively working on the issue. We are still in the process of investigating and analyzing the root cause to ensure we can provide a proper resolution.

We will keep you updated as soon as we have more concrete information or progress to share. If you have any additional details or questions in the meantime, please don’t hesitate to reach out.

Best regards

**Comment by adyen-integrations-support** [comment]
Hey,

Once we have more information, we will let you know.

Thank you for your patience and understanding.

Best regards.

**Comment by vasily-polonsky** [comment]
Hi there,
do you need help? Bug was introduced in this PR, commented line https://github.com/Adyen/adyen-commercetools/pull/1183/files#r1910300105
New versions are released, but they can not be used by us, as lambda function is just crashes when it starting with Runtime error

**Comment by adyen-integrations-support** [comment]
Hey @vasily-polonsky 

Thank you for your help.

We wanted to inform you that our team has added the logger parameter for serverless and resolved the issue.

This fix will be included in the next release, scheduled for this week.

Best regards.

**Comment by adyen-integrations-support** [comment]
Hey @vasily-polonsky 

The new plugin version 11.5.10 has been released https://github.com/Adyen/adyen-commercetools/releases/tag/v11.5.10.

Best regards.
